spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:mypay_money
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    data:
      host: 127.0.0.1
      port: 6379
