spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/mypay_money
    username: myuser
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    data:
      host: 127.0.0.1
      port: 6379
