spring:
  application:
    name: api-gateway

  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:9000/
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
        - id: money-service
          uri: http://localhost:10000/
          predicates:
            - Path=/moneys/health/ping
            - Method=GET
          filters:
            - RewritePath=/moneys/?(?<segment>.*), /$\{segment}
        - id: money-service
          uri: http://localhost:10000/
          predicates:
            - Path=/moneys/**
          filters:
            - RewritePath=/moneys/?(?<segment>.*), /$\{segment}
            - PreAuthGatewayFilter
            - PostAuthGatewayFilter

app:
  auth-check-url: http://localhost:9000/v1/auths/check

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: development
