spring:
  application:
    name: api-gateway

  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: prometheus

---
spring:
  config:
    activate:
      on-profile: local

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:9000/
          predicates:
            - Path=/accounts/**, /accounts/actuator/**
          filters:
            - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
        - id: money-service
          uri: http://localhost:10000/
          predicates:
            - Path=/money/docs/index.html, /money/health/ping, /money/actuator/**
            - Method=GET
          filters:
            - RewritePath=/money/?(?<segment>.*), /$\{segment}
        - id: money-service
          uri: http://localhost:10000/
          predicates:
            - Path=/money/**
          filters:
            - RewritePath=/money/?(?<segment>.*), /$\{segment}
            - PreAuthGatewayFilter
            - PostAuthGatewayFilter

app:
  auth-check-url: http://localhost:9000/v1/auths/check

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: development
