spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:mypay_account
    username: sa
    password:
    driver-class-name: org.h2.Driver